version: "3.9"

services:
  server:
    build:
      context: ./backend/area-back
    ports:
      - "3000:3000"
    container_name: server_service
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres_service
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  client_web:
    build:
      context: ./frontend/area-front
    ports:
      - "8080:8080"
    container_name: client_web_service
    depends_on:
      - server