name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Backend Dependencies
      run: cd backend/area-back && npm install

    - name: Install Frontend Dependencies
      run: cd frontend/area-front && npm install

    - name: Run Code Formatter
      run: |
        cd backend/area-back && npx prettier --write .
        cd ../../frontend/area-front && npx prettier --write .

  build-apk:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Frontend Dependencies
      run: cd frontend/area-front && npm install

    - name: Build React App
      run: |
        cd frontend/area-front && npm run build

    - name: Install Capacitor CLI
      run: |
        npm install @capacitor/core @capacitor/cli --prefix frontend/area-front

    - name: Sync Capacitor Project
      run: |
        cd frontend/area-front && npx cap sync android

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y android-sdk gradle
        export ANDROID_HOME=/usr/lib/android-sdk
        export PATH=$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH

    - name: Build APK
      working-directory: frontend/area-front/android
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: frontend/area-front/android/app/build/outputs/apk/debug/app-debug.apk

  deploy:
    needs: [build-and-test, build-apk]
    runs-on: ubuntu-latest

    steps:
    - name: SSH and Pull Latest Changes
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/Flowfy
          git pull
          git push --mirror original-repo
          git ls-remote original-repo
          cd ~/B-DEV-500-RUN-5-2-area-cedric.roulof/
          docker-compose down --volumes --remove-orphans
          git pull origin main
          cd ~/B-DEV-500-RUN-5-2-area-cedric.roulof/backend/area-back
          npm install
          cd ~/B-DEV-500-RUN-5-2-area-cedric.roulof/frontend/area-front
          npm install
          cd ~/B-DEV-500-RUN-5-2-area-cedric.roulof/
          docker-compose up --build -d
